"""INetSim sink for lab egress containment.

The :class:`InetSimSink` is a thin wrapper that (a) emits a minimal INetSim
``inetsim.conf`` for a given run, and (b) exposes an :meth:`attempts`
hook the executor can use to verify what (if anything) reached the sink.

The :class:`InMemoryEgressSink` is the test-only implementation used in
CI; it records every connection attempt in process memory.

The module also provides :func:`render_inetsim_config` for ops use - the
generated config restricts INetSim to listen on the lab subnet only and
disables every service that would phone home.
"""

from __future__ import annotations

import threading
from abc import ABC, abstractmethod
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import UTC, datetime

DEFAULT_INETSIM_SERVICES: tuple[str, ...] = (
    "dns",
    "http",
    "https",
    "smtp",
    "smtps",
    "pop3",
    "ftp",
    "tftp",
    "irc",
    "ntp",
    "finger",
    "ident",
    "syslog",
    "time",
    "daytime",
    "echo",
    "discard",
    "quotd",
    "chargen",
)


@dataclass(frozen=True)
class EgressAttempt:
    """A single observed connection attempt to the sink."""

    timestamp: datetime
    source: str
    destination: str
    protocol: str
    payload_excerpt: str = ""


class EgressSink(ABC):
    """Lab-side sink that absorbs all C2-style traffic."""

    @abstractmethod
    def record(self, attempt: EgressAttempt) -> None:
        """Record an observed egress attempt."""

    @abstractmethod
    def attempts(self) -> tuple[EgressAttempt, ...]:
        """Return all attempts observed so far (oldest first)."""

    def assert_no_real_egress(self) -> None:
        """Raise if any attempt has a destination that isn't the sink itself.

        Concrete implementations may override; the default permits all
        attempts since the sink, by definition, captures them.
        """
        return None


class InMemoryEgressSink(EgressSink):
    """Thread-safe in-process sink for tests."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._attempts: list[EgressAttempt] = []

    def record(self, attempt: EgressAttempt) -> None:
        with self._lock:
            self._attempts.append(attempt)

    def attempts(self) -> tuple[EgressAttempt, ...]:
        with self._lock:
            return tuple(self._attempts)

    def __len__(self) -> int:
        with self._lock:
            return len(self._attempts)


@dataclass
class InetSimSink(EgressSink):
    """Adapter for an external INetSim instance.

    Phase 3 ships the config-rendering and observability hooks; live
    deployment (running INetSim in the lab) is operationally configured
    via ``infra/docker-compose.lab.yml`` and is wired in Phase 3.5.
    """

    bind_address: str
    service_address: str
    services: tuple[str, ...] = field(default_factory=lambda: DEFAULT_INETSIM_SERVICES)
    _observed: list[EgressAttempt] = field(default_factory=list, init=False)

    def record(self, attempt: EgressAttempt) -> None:
        self._observed.append(attempt)

    def attempts(self) -> tuple[EgressAttempt, ...]:
        return tuple(self._observed)

    def render_config(self) -> str:
        return render_inetsim_config(
            bind_address=self.bind_address,
            service_address=self.service_address,
            services=self.services,
        )

    @classmethod
    def from_observations(
        cls, *, bind_address: str, service_address: str, observed: Iterable[EgressAttempt]
    ) -> InetSimSink:
        sink = cls(bind_address=bind_address, service_address=service_address)
        for attempt in observed:
            sink.record(attempt)
        return sink


def render_inetsim_config(
    *,
    bind_address: str,
    service_address: str,
    services: tuple[str, ...] = DEFAULT_INETSIM_SERVICES,
) -> str:
    """Render a minimal, deny-by-default INetSim config.

    The config (a) binds INetSim to the lab subnet only, and (b) enables
    only the supplied services - leaving every other service disabled.
    Generated configs are reproducible for the same arguments so they can
    be content-hashed into audit events.
    """
    if not bind_address or not service_address:
        raise ValueError("bind_address and service_address must be non-empty")
    if not services:
        raise ValueError("at least one service must be enabled")
    header = (
        f"# Auto-generated by threat-emulation at "
        f"{datetime.now(UTC).isoformat(timespec='seconds')}\n"
        f"# Deny-by-default lab egress containment.\n"
    )
    bind = (
        f"service_bind_address {bind_address}\n"
        f"service_run {' '.join(services)}\n"
        f"dns_default_ip {service_address}\n"
        f"http_fakemode_static_extensions exe pdf doc docx zip\n"
    )
    safety = (
        "# Hard rule: never connect outbound from this host.\n"
        "# (Operationally enforced by the lab network policy.)\n"
    )
    return header + bind + safety
